In [3]:
def add_one(number: int):
    return number + 1

add_one(number="hello") # Crashes later with a messy error

TypeError: can only concatenate str (not "int") to str

In Python, you can "hint" at what type of data a function should get. For example:
def save_json(path: Path, data: dict):
Usually, Python ignores these hints. You could pass a number instead of a dictionary, and Python wouldn't complain until the code actually crashes deep inside the function.

`@ensure_annotations is a decorator that forces Python to check these hints while the code is running.`

    1.Stop Bugs Instantly
    2.Clearer Error
    3.Better Teamwork

In [15]:
from ensure import ensure_annotations

@ensure_annotations
def add_numbers(a: int, b: int) -> int:
    return a + b

# This works fine
add_numbers(10, 20) 


30

In [16]:
# This will raise an "EnsureError" immediately because "20" is a string
add_numbers(10, "20")

EnsureError: Argument b of type <class 'str'> to <function add_numbers at 0x7f006c670a40> does not match annotation type <class 'int'>

In standard Python, if you have a dictionary, you have to access the data using square brackets and quotes:
data["database"]["port"]

`ConfigBox is a wrapper that allows you to access dictionary keys as if they were attributes (using a dot):`

    data.database.port

Standard: print(config['artifacts']['root_dir'])

ConfigBox: print(config.artifacts.root_dir)

``` bash
Feature         Standard Python Dictionary,     With ConfigBox
AccessStyle,    d['key'],                       d.key
Syntax,         Cluttered (quotes/brackets),    Clean (dot notation)
SpeedtoType     Slower,                         Faster

In [4]:
from box import ConfigBox

# A normal dictionary
d = {"name": "Tumar-AI", "version": 3}

# Convert it
d2 = ConfigBox(d)

# Now you can use dots!
print(d2.name)    # XrayAI
print(d2.version) # Output: 3

Tumar-AI
3


In [19]:
import numpy as np

mask = np.array([
[1,0,1],
[0,1,0],
[1,1,0]
])

print("Original shape:", mask.shape)

flat = mask.reshape(-1)

print("Flattened:", flat)
print("Shape:", flat.shape)

Original shape: (3, 3)
Flattened: [1 0 1 0 1 0 1 1 0]
Shape: (9,)


Tensor Dimensions

| Data Type       | Example       | Dimension |
| --------------- | ------------- | --------- |
| Scalar          | 5             | 0D        |
| Vector          | [1,2,3]       | 1D        |
| Matrix          | [[1,2],[3,4]] | 2D        |
| Image           | 224×224×3     | 3D        |
| Batch of images | 32×224×224×3  | 4D        |


Why Tensor Use In Deep Learning?

Because tensors support:

| Feature               | Why Important   |
| --------------------- | --------------- |
| GPU computation       | Faster training |
| Parallel computation  | Large datasets  |
| Auto differentiation  | Backpropagation |
| High dimensional data | Images, video   |


Real ML Example

Image segmentation training:

    Input image

    Shape:
    (256, 256, 3)

    After batch:

    (16, 256, 256, 3)

    Meaning

    16 images per batch

In [20]:
import numpy as np

x = np.array([1,2,3])
print(x)

[1 2 3]


In [21]:
import tensorflow as tf

x = tf.constant([1,2,3])
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [22]:
import torch

x = torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [23]:
from keras import ops

x = ops.array([[1,2],[3,4]])
print(x)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
